### ISSUE TITLE
Improve Helios Preset Composition

### ISSUE THREAD

**Issue by Lairdd1989** [Theseus-Aegis/MissionTemplate#40]
Inlcude following in the `Huron Fuel Container` to ensure hose can reach helicopters in enclosed spaces.
Not sure if applicable to the Ammo or Repair Huron containers

`this setVariable ["ace_refuel_hoseLength", 50];`

**Comment by jonpas** [comment]
> Not sure if applicable to the Ammo or Repair Huron containers

**Comment by jonpas** [comment]
On another thought, I would maybe rather see higher default value for hose length (it is a CBA Setting).

**Comment by TyroneMF** [comment]
Done via setting in [TAC Mods](https://github.com/Theseus-Aegis/Mods/pull/484)
