### ISSUE TITLE
Set Base as ACE3 Medical Facility

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/MissionTemplate#76]
Our home base should be an ACE3 Medical Facility which boosts medic training to a higher level (everyone becomes a Medic in our circumstances).

Not sure if it should be a building or an area (defined by some "building").

**Comment by JoramD0** [comment]
Could set it from the medical box, saves from having to add another building/object.

**Comment by jonpas** [comment]
This has [already been done by @Kresky](https://github.com/Theseus-Aegis/MissionTemplate/releases/tag/v2.2.5) and subsequently copied by @TyroneMF into the new compositions.
